Pod::Spec.new do |s|
  s.name             = 'FBirdAdSDK'
  s.version          = '1.3.5'
  s.summary          = 'FBirdAdSDK 是一个广告集成 SDK'
  s.description      = 'FBirdAdSDK 提供开屏、插屏、信息流和激励视频广告能力，并内置 Taku / GroMore 聚合 adapter。'
  s.homepage         = 'https://sdk.dmpdsp.com/'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Your Name' => 'wjl@dmpdsp.com' }
  s.source           = { :git => 'https://github.com/queli1990/FBirdAdSdk-iOS.git', :tag => s.version.to_s }
  s.ios.deployment_target = '13.0'
  s.frameworks       = 'UIKit', 'AVFoundation', 'CoreTelephony'

  # Binary framework (regenerated by build_xcframework.sh)
  s.vendored_frameworks = 'XCFramework/FBirdAdSDK.xcframework'

  # Canonical resource bundle, checked into git as the single source of truth.
  # The build script copies this same bundle into XCFramework/Resources/ for
  # consumers who integrate the XCFramework directly (without CocoaPods).
  s.resources = 'XCFramework/Resources/FBirdAdSDKBundle.bundle'

  # External dependencies
  s.dependency 'lottie-ios', '~> 4.4.0'
  s.dependency 'AnyThinkiOS'
  s.dependency 'Ads-CN/BUAdSDK', '7.6.1.7'
  s.dependency 'Ads-CN/BUAdLive-Framework', '7.6.1.7'
  s.dependency 'Ads-CN/CSJMediation', '7.6.1.7'

  # Static framework: avoid duplicate-symbol issues when host uses use_frameworks!
  s.static_framework = true

end
