Pod::Spec.new do |s|
  s.name             = 'FBirdAdSDK'
  s.version          = '0.0.2'
  s.summary          = 'FBirdAdSDK 是一个广告集成 SDK'
  s.description      = 'FBirdAdSDK 提供了开屏、插屏、信息流和激励视频等广告类型的集成能力'
  s.homepage         = 'https://sdk.dmpdsp.com/'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Your Name' => 'wjl@dmpdsp.com' }
  s.source           = { :git => 'https://github.com/queli1990/FBirdAdSdk-iOS.git', :tag => s.version.to_s }
  s.ios.deployment_target = '12.0'
  s.frameworks       = 'UIKit', 'AVFoundation', 'CoreTelephony'
  
  # Binary framework (regenerated by build_xcframework.sh)
  s.vendored_frameworks = 'XCFramework/FBirdAdSDK.xcframework'

  # Canonical resource bundle, checked into git as the single source of truth.
  # The build script copies this same bundle into XCFramework/Resources/ for
  # consumers who integrate the XCFramework directly (without CocoaPods).
  s.resources = 'XCFramework/Resources/FBirdAdSDKBundle.bundle'

  # Static framework: avoid duplicate-symbol issues when host uses use_frameworks!
  s.static_framework = true

end
